### ISSUE TITLE
nuxt+vuetify-nuxt-module+vue-macros combination of components has stopped working

### ISSUE THREAD

**Issue by AndreyKindin** [vue-macros/vue-macros#807]
Hello, 
recently, the combination of vuetify+nuxt(-module)+vue-macros stopped working. 
If I remove Vue macros from the modules, it seems to work. I'm not sure if I'm in the right place with the bug, but maybe just as a heads up that the bug exists.

P.S.:
If I try to implement the whole thing without the vuetify-nuxt-module, but rather via the plugin, I get the error:
Cannot start nuxt:  Vuetify plugin must be loaded after the vue plugin                                     

  at configResolved (node_modules/vite-plugin-vuetify/dist/index.cjs:29:15)
  at node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66327:67
  at Array.map (<anonymous>)
  at resolveConfig (node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66327:53)
  at async _createServer (node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:62687:18)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:745:24)
  at async withLogs (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1835:3)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1826:3)
  at async bundle (node_modules/nuxt/dist/index.mjs:5888:5)
  at async build (node_modules/nuxt/dist/index.mjs:5763:3)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5xyynj?file=nuxt.config.ts

### System Info

```Shell
my wsl
 System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 25.16 GB / 31.06 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.14.3 - /mnt/c/Users/akind/AppData/Roaming/npm/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun

stackblitz
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@sxzz the problem is about removing the `vite:vue` plugin, any plugin depending on the position will be broken: there is no way to fix this on Nuxt for example since the VueMacros plugin cannot be detected (has no name), check this SB reproduction https://stackblitz.com/edit/nuxt-starter-jq6cno?file=nuxt.config.ts,app.vue,package.json (inline module in nuxt config. file)

**Comment by sxzz** [comment]
It may fixed via 7ec74c0d7fb6bb4730aa4e07f82dc9cceebf8d77

**Comment by sxzz** [comment]
Fixed & released as `@vue-macros/nuxt@1.11.13`.

See also https://github.com/vuetifyjs/nuxt-module/issues/275#issuecomment-2345050191

**Comment by AndreyKindin** [comment]
Thanks @sxzz and @userquin for the release, 
but as far as I understand it, it only works in combination with
‘vuetify-nuxt-module’: ‘https://pkg.pr.new/vuetify-nuxt-module@276’,
If I integrate vuetify via plugin in nuxt, it still doesn't work.
Here is the example,
https://stackblitz.com/edit/nuxt-starter-mwe9yw?file=nuxt.config.ts
you get the following errors

 ERROR  Cannot restart nuxt:  Vuetify plugin must be loaded after the vue plugin                                                                             09:44:55

  at configResolved (node_modules/vite-plugin-vuetify/dist/index.cjs:29:15)
  at eval (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:66390:67)
  at resolveConfig (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:66390:53)
  at async _createServer (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:62746:18)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:767:24)
  at async withLogs (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1857:3)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1848:3)
  at async bundle (node_modules/nuxt/dist/index.mjs:5905:5)
  at async build (node_modules/nuxt/dist/index.mjs:5780:3)

**Comment by userquin** [comment]
You need to find the plugin array from vue macros with the vite:vue and move the vuetify import plugin after it, you need to replace the extendConfig with configResolved nuxt hook.

**Comment by userquin** [comment]
With latest release of nuxt macros you only need to change the nuxt hook, the logic to find the `vite:vue` plugin is the same

**Comment by sxzz** [comment]
Vue Macros recently switched to `configResolved` from `extendConfig` because `vite:vue` is inserted only after `extendConfig`. See https://github.com/vue-macros/vue-macros/pull/787.

In the latest commit 575ca135b0d9c1dff4b327c6972461a1e75cc986, I optimized the insertion logic to maintain items in their original positions instead of moving them to the end.

**Comment by sxzz** [comment]
Released as `@vue-macros/nuxt@1.11.14`
